/** Action-queue kind vocabulary shared by queue storage and recipe rendering. */
export const ACTION_QUEUE_KINDS = [
  'failed',
  'steward-repeat',
  'cancelled-blocker-cascade',
  'diagnose-inconclusive',
  'daemon-killed',
  'coder-question',
  'daemon-died',
  'stale-worktree',
  'worktree-ahead',
  'prerequisite-failed',
  'draft-proposal',
  'slices-dropped',
  'slice-failed',
  'hitl-slice-needs-operator',
  'awaiting-validation',
  'awaiting-validation-preview-gone',
  'awaiting-human',
  'behaviour-unverified',
  'subscriber-stalled',
  'observability-store-oversize',
  'orphaned-origin',
  'phantom-task',
  'outbox-lag',
  'reflect-recommended',
  'done-with-unmerged-commits',
  'api-outage',
  'daemon-code-drift',
  'workflow-install-drift',
  'provider-rate-limited',
  'gate-broken',
  'verify-uncovered',
  'workflow-draft-pending',
  'gate-enrichment',
  'budget-window',
  'budget-arc',
  'scorer-suggested',
  'promotion-decision',
  'tool-promotion',
  'arc-verification-failed',
  'signature-storm',
  'gate-enrichment-stale',
  'env-incident',
  'stale-queued',
  'stale-queued-summary',
  'spend-control-notice',
  'scheduling-decision',
  'requeue-warning',
] as const

export type ActionQueueKind = (typeof ACTION_QUEUE_KINDS)[number]

export const isActionQueueKind = (s: unknown): s is ActionQueueKind =>
  ACTION_QUEUE_KINDS.includes(s as ActionQueueKind)
