/**
 * uninstall — core logic for `mars uninstall`.
 *
 * Deletes the wrapper binary first, then the source clone directory, with
 * graceful partial-state handling.  All side effects (filesystem I/O,
 * user confirmation, logging) are injected so the function is fully
 * testable without touching the real filesystem.
 *
 * Two pure path-resolution helpers (`resolveUninstallPaths`,
 * `findWrapperFor`) live alongside the run function so the CLI entry can
 * locate the wrapper robustly — by matching the running cli entry point
 * against wrappers on PATH — rather than relying on a brittle `which mars`
 * lookup.
 */

import { accessSync, constants, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

// ---------------------------------------------------------------------------
// Path resolution helpers (pure)
// ---------------------------------------------------------------------------

/** The two on-disk locations that `mars uninstall` removes. */
export interface UninstallPaths {
  /** Resolved path to the mars binary (e.g. /usr/local/bin/mars). */
  binPath: string
  /** Resolved path to the mars source clone / installation directory. */
  srcDir: string
}

/**
 * Parse the `exec` line of a dev-install wrapper to extract the TypeScript
 * entry path, then derive the source clone root from it.
 *
 * The dev-install wrapper (generated by install-dev.sh) looks like:
 *   exec "/path/to/tsx" "/path/to/orchestrator/src/cli.ts" "$@"
 *
 * The source clone root is three directories above cli.ts:
 *   cli.ts -> src/ -> orchestrator/ -> <clone root>
 */
function parseSrcDirFromWrapper(content: string): string {
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed.startsWith('exec ')) continue
    const match = trimmed.match(/exec\s+"[^"]+"\s+"([^"]+)"/)
    if (match?.[1]) {
      return dirname(dirname(dirname(match[1])))
    }
  }
  throw new Error(
    'could not parse entry path from wrapper — expected an exec line like:\n' +
      '  exec "tsx" "/path/to/orchestrator/src/cli.ts" "$@"',
  )
}

/**
 * Resolve the pair of paths that `mars uninstall` would remove, given the
 * absolute (or relative) path to a dev-install mars wrapper.
 *
 * The wrapper itself is `binPath`; the clone it points into is `srcDir`.
 */
export function resolveUninstallPaths(wrapperPath: string): UninstallPaths {
  const binPath = resolve(wrapperPath)
  const content = readFileSync(binPath, 'utf8')
  const srcDir = parseSrcDirFromWrapper(content)
  return { binPath, srcDir }
}

/**
 * Walk the directories on the supplied PATH-like string and return the first
 * executable named `mars` whose contents reference `cliEntryPath`.
 *
 * The PATH lookup is only a way to locate the wrapper on disk — the resolved
 * binary is matched by the running entry point (`cliEntryPath`), not by an
 * environment variable, so two installs on PATH never confuse the lookup.
 *
 * Returns null when no matching wrapper is found (e.g. running directly via
 * `tsx src/cli.ts` without an installed wrapper).
 */
export function findWrapperFor(
  cliEntryPath: string,
  pathEnv: string = process.env.PATH ?? '',
): string | null {
  for (const dir of pathEnv.split(':')) {
    if (!dir) continue
    const candidate = join(dir, 'mars')
    try {
      accessSync(candidate, constants.X_OK)
      const content = readFileSync(candidate, 'utf8')
      if (content.includes(cliEntryPath)) {
        return candidate
      }
    } catch {
      // not executable / not readable — skip
    }
  }
  return null
}

// ---------------------------------------------------------------------------
// Deletion flow (slice 4)
// ---------------------------------------------------------------------------

export interface UninstallDeps {
  /** Return true when the given path exists on disk. */
  exists: (p: string) => boolean
  /** Remove a single file. */
  removeFile: (p: string) => Promise<void>
  /** Recursively remove a directory. */
  removeDir: (p: string) => Promise<void>
  /** Prompt the user; return true to proceed, false to cancel. */
  confirm: () => Promise<boolean>
  /** Emit a human-readable line of output. */
  log: (msg: string) => void
}

export type UninstallOutcome =
  | 'cancelled'
  | 'full-success'
  | 'source-already-absent'
  | 'wrapper-already-absent'

export interface UninstallResult {
  outcome: UninstallOutcome
}

/**
 * Run the uninstall sequence.
 *
 * Deletion order: wrapper first, then source clone.  Per-repo .mars/ and
 * .worktrees/ directories are never touched — only the two paths passed in.
 *
 * @param wrapperPath  Absolute path to the installed `mars` wrapper binary.
 * @param cloneDir     Absolute path to the source clone (the repo root).
 * @param deps         Injected I/O dependencies.
 */
export async function runUninstall(
  wrapperPath: string,
  cloneDir: string,
  deps: UninstallDeps,
): Promise<UninstallResult> {
  const confirmed = await deps.confirm()
  if (!confirmed) {
    return { outcome: 'cancelled' }
  }

  const wrapperExists = deps.exists(wrapperPath)
  const cloneExists = deps.exists(cloneDir)

  // --- wrapper (always first) ---
  if (wrapperExists) {
    await deps.removeFile(wrapperPath)
  } else {
    deps.log(`wrapper already absent: ${wrapperPath}`)
  }

  // --- source clone (always second, after wrapper) ---
  if (cloneExists) {
    await deps.removeDir(cloneDir)
  } else {
    deps.log(`source clone already absent: ${cloneDir}`)
  }

  // --- outcome + PATH reminder ---
  if (!wrapperExists && cloneExists) {
    deps.log(
      `Done. Note: your shell rc may still export the install bin directory on PATH. ` +
        `Remove or update that export in ~/.bashrc / ~/.zshrc if you no longer want it.`,
    )
    return { outcome: 'wrapper-already-absent' }
  }

  if (wrapperExists && !cloneExists) {
    deps.log(
      `Done. Note: your shell rc may still export the install bin directory on PATH. ` +
        `Remove or update that export in ~/.bashrc / ~/.zshrc if you no longer want it.`,
    )
    return { outcome: 'source-already-absent' }
  }

  deps.log(
    `Uninstalled. Note: your shell rc may still export the install bin directory on PATH. ` +
      `Remove or update that export in ~/.bashrc / ~/.zshrc if you no longer want it.`,
  )
  return { outcome: 'full-success' }
}
