import { describe, it, expect } from 'vitest'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  findWrapperFor,
  resolveUninstallPaths,
  runUninstall,
} from './uninstall.js'
import type { UninstallDeps } from './uninstall.js'

// ---------------------------------------------------------------------------
// Test helpers — slice-4 deletion API
// ---------------------------------------------------------------------------

/** Build an UninstallDeps where both paths exist and confirm returns true. */
function makeDeps(
  overrides: Partial<UninstallDeps> & { existingPaths?: Set<string> } = {},
): UninstallDeps & { removed: string[]; logged: string[] } {
  const removed: string[] = []
  const logged: string[] = []
  const existingPaths: Set<string> =
    overrides.existingPaths ??
    new Set(['/home/user/.local/bin/mars', '/home/user/mars-framework'])

  return {
    removed,
    logged,
    exists: overrides.exists ?? ((p) => existingPaths.has(p)),
    removeFile:
      overrides.removeFile ??
      (async (p) => {
        removed.push(`file:${p}`)
      }),
    removeDir:
      overrides.removeDir ??
      (async (p) => {
        removed.push(`dir:${p}`)
      }),
    confirm: overrides.confirm ?? (async () => true),
    log:
      overrides.log ??
      ((msg) => {
        logged.push(msg)
      }),
  }
}

const WRAPPER = '/home/user/.local/bin/mars'
const CLONE = '/home/user/mars-framework'

// Build a dev-install–style wrapper script at <dir>/mars pointing at the
// supplied TypeScript entry path. Returns the absolute wrapper path.
function makeWrapper(dir: string, entryPath: string): string {
  const wrapperPath = join(dir, 'mars')
  writeFileSync(
    wrapperPath,
    [
      '#!/usr/bin/env bash',
      '# Auto-generated by mars-framework/install-dev.sh — do not edit.',
      `exec "/fake/tsx" "${entryPath}" "$@"`,
      '',
    ].join('\n'),
    { mode: 0o755 },
  )
  return wrapperPath
}

// ---------------------------------------------------------------------------
// runUninstall — full success
// ---------------------------------------------------------------------------

describe('runUninstall — full success', () => {
  it('removes the wrapper file on a confirmed full-success run', async () => {
    const deps = makeDeps()
    const result = await runUninstall(WRAPPER, CLONE, deps)

    expect(result.outcome).toBe('full-success')
    expect(deps.removed).toContain(`file:${WRAPPER}`)
  })

  it('removes the source clone directory on a confirmed full-success run', async () => {
    const deps = makeDeps()
    const result = await runUninstall(WRAPPER, CLONE, deps)

    expect(result.outcome).toBe('full-success')
    expect(deps.removed).toContain(`dir:${CLONE}`)
  })

  it('prints a shell rc PATH reminder on full success', async () => {
    const deps = makeDeps()
    await runUninstall(WRAPPER, CLONE, deps)

    const reminder = deps.logged.some((msg) =>
      /shell\s+rc|\.bashrc|\.zshrc|PATH/i.test(msg),
    )
    expect(reminder).toBe(true)
  })
})

describe('runUninstall — deletion order invariant', () => {
  it('wrapper is deleted before the source clone is attempted', async () => {
    // Make removeDir throw — after the throw, verify the wrapper is already gone.
    const callOrder: string[] = []
    const deps = makeDeps({
      removeFile: async (p) => {
        callOrder.push(`file:${p}`)
      },
      removeDir: async (_p) => {
        // Simulate a failure partway through; the wrapper must already be removed.
        throw new Error('simulated clone removal failure')
      },
    })

    await expect(runUninstall(WRAPPER, CLONE, deps)).rejects.toThrow(
      'simulated clone removal failure',
    )

    // Wrapper was already deleted before removeDir was attempted.
    expect(callOrder).toContain(`file:${WRAPPER}`)
  })
})

describe('runUninstall — partial-state: source clone already absent', () => {
  it('still removes the wrapper when the source clone is already gone', async () => {
    const deps = makeDeps({
      existingPaths: new Set([WRAPPER]), // clone is absent
    })
    const result = await runUninstall(WRAPPER, CLONE, deps)

    expect(result.outcome).toBe('source-already-absent')
    expect(deps.removed).toContain(`file:${WRAPPER}`)
  })

  it('prints "source clone already absent" when clone is missing', async () => {
    const deps = makeDeps({
      existingPaths: new Set([WRAPPER]),
    })
    await runUninstall(WRAPPER, CLONE, deps)

    const mentioned = deps.logged.some((msg) =>
      /source clone already absent/i.test(msg),
    )
    expect(mentioned).toBe(true)
  })

  it('exits 0 (no thrown error) when source clone is already absent', async () => {
    const deps = makeDeps({
      existingPaths: new Set([WRAPPER]),
    })
    await expect(runUninstall(WRAPPER, CLONE, deps)).resolves.not.toThrow()
  })

  it('prints a shell rc PATH reminder when source clone is already absent', async () => {
    const deps = makeDeps({
      existingPaths: new Set([WRAPPER]),
    })
    await runUninstall(WRAPPER, CLONE, deps)

    const reminder = deps.logged.some((msg) =>
      /shell\s+rc|\.bashrc|\.zshrc|PATH/i.test(msg),
    )
    expect(reminder).toBe(true)
  })
})

describe('runUninstall — partial-state: wrapper already absent', () => {
  it('still removes the source clone when the wrapper is already gone', async () => {
    const deps = makeDeps({
      existingPaths: new Set([CLONE]), // wrapper is absent
    })
    const result = await runUninstall(WRAPPER, CLONE, deps)

    expect(result.outcome).toBe('wrapper-already-absent')
    expect(deps.removed).toContain(`dir:${CLONE}`)
  })

  it('prints "wrapper already absent" when wrapper is missing', async () => {
    const deps = makeDeps({
      existingPaths: new Set([CLONE]),
    })
    await runUninstall(WRAPPER, CLONE, deps)

    const mentioned = deps.logged.some((msg) =>
      /wrapper already absent/i.test(msg),
    )
    expect(mentioned).toBe(true)
  })

  it('prints a shell rc PATH reminder when wrapper is already absent', async () => {
    const deps = makeDeps({
      existingPaths: new Set([CLONE]),
    })
    await runUninstall(WRAPPER, CLONE, deps)

    const reminder = deps.logged.some((msg) =>
      /shell\s+rc|\.bashrc|\.zshrc|PATH/i.test(msg),
    )
    expect(reminder).toBe(true)
  })
})

describe('runUninstall — no .mars/ directories touched', () => {
  it('never passes a .mars/ or .worktrees/ path to removeFile or removeDir', async () => {
    const touched: string[] = []
    const deps = makeDeps({
      removeFile: async (p) => {
        touched.push(p)
      },
      removeDir: async (p) => {
        touched.push(p)
      },
    })
    await runUninstall(WRAPPER, CLONE, deps)

    for (const p of touched) {
      expect(p).not.toMatch(/\.(mars|worktrees)/)
    }
  })
})

describe('runUninstall — cancelled', () => {
  it('returns cancelled outcome when user does not confirm', async () => {
    const deps = makeDeps({
      confirm: async () => false,
    })
    const result = await runUninstall(WRAPPER, CLONE, deps)

    expect(result.outcome).toBe('cancelled')
    expect(deps.removed).toHaveLength(0)
  })
})

// ---------------------------------------------------------------------------
// resolveUninstallPaths — fixture wrapper
// ---------------------------------------------------------------------------

describe('resolveUninstallPaths', () => {
  it('returns binPath = wrapper path and srcDir = clone root derived from the wrapper', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mars-uninstall-resolve-'))
    try {
      const fakeCloneRoot = '/home/tester/mars-framework'
      const fakeEntry = `${fakeCloneRoot}/orchestrator/src/cli.ts`
      const wrapperPath = makeWrapper(dir, fakeEntry)

      const paths = resolveUninstallPaths(wrapperPath)

      expect(paths).toEqual({
        binPath: wrapperPath,
        srcDir: fakeCloneRoot,
      })
    } finally {
      rmSync(dir, { recursive: true })
    }
  })

  it('resolves a relative wrapper path to an absolute binPath', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mars-uninstall-resolve-'))
    try {
      const fakeEntry = '/srv/mars-framework/orchestrator/src/cli.ts'
      const wrapperPath = makeWrapper(dir, fakeEntry)

      const paths = resolveUninstallPaths(wrapperPath)

      expect(paths.binPath.startsWith('/')).toBe(true)
      expect(paths.binPath).toBe(wrapperPath)
    } finally {
      rmSync(dir, { recursive: true })
    }
  })

  it('throws a helpful error when the wrapper has no exec line', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mars-uninstall-resolve-'))
    try {
      const wrapperPath = join(dir, 'mars')
      writeFileSync(wrapperPath, '#!/usr/bin/env bash\necho hi\n', { mode: 0o755 })
      expect(() => resolveUninstallPaths(wrapperPath)).toThrow(/exec/i)
    } finally {
      rmSync(dir, { recursive: true })
    }
  })
})

// ---------------------------------------------------------------------------
// findWrapperFor — PATH search keyed by running entry point
// ---------------------------------------------------------------------------

describe('findWrapperFor', () => {
  it('returns the wrapper whose contents reference the running cli entry', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mars-uninstall-find-'))
    try {
      const fakeEntry = '/opt/mars/orchestrator/src/cli.ts'
      const wrapperPath = makeWrapper(dir, fakeEntry)

      const found = findWrapperFor(fakeEntry, dir)
      expect(found).toBe(wrapperPath)
    } finally {
      rmSync(dir, { recursive: true })
    }
  })

  it('returns null when no wrapper on PATH references the entry', () => {
    const dir = mkdtempSync(join(tmpdir(), 'mars-uninstall-find-'))
    try {
      makeWrapper(dir, '/somewhere/else/cli.ts')
      const found = findWrapperFor('/opt/mars/orchestrator/src/cli.ts', dir)
      expect(found).toBeNull()
    } finally {
      rmSync(dir, { recursive: true })
    }
  })
})
