#!/usr/bin/env bash
# Install the orchestrator dev CLI globally.
# Edits to orchestrator/src/** go live immediately (no rebuild) because the
# wrapper runs TypeScript via `tsx` from a fixed source directory.

set -euo pipefail

CMD_NAME="${ORCHESTRATOR_CMD:-mars}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORCH_DIR="$REPO_ROOT/orchestrator"
ENTRY="$ORCH_DIR/src/cli.ts"
TSX_BIN="$ORCH_DIR/node_modules/.bin/tsx"

if [[ ! -f "$ENTRY" ]]; then
  echo "error: cli entry not found at $ENTRY" >&2
  exit 1
fi

if [[ ! -x "$TSX_BIN" ]]; then
  echo "tsx not found at $TSX_BIN — running 'npm install' in $ORCH_DIR" >&2
  (cd "$ORCH_DIR" && npm install)
fi

pick_bin_dir() {
  if [[ -n "${PREFIX:-}" ]]; then
    echo "$PREFIX/bin"
    return
  fi
  for d in "$HOME/.local/bin" "/usr/local/bin" "/opt/homebrew/bin"; do
    if [[ -d "$d" && -w "$d" ]]; then
      echo "$d"
      return
    fi
  done
  mkdir -p "$HOME/.local/bin"
  echo "$HOME/.local/bin"
}

BIN_DIR="$(pick_bin_dir)"
WRAPPER="$BIN_DIR/$CMD_NAME"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by mars-framework/install.sh — do not edit.
# Runs the orchestrator CLI from source via tsx; edits in
# $ORCH_DIR/src are live.
exec "$TSX_BIN" "$ENTRY" "\$@"
EOF
chmod +x "$WRAPPER"

echo "installed: $WRAPPER -> $ENTRY (via $TSX_BIN)"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo
    echo "warning: $BIN_DIR is not on your PATH."
    echo "add this to your shell rc:"
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
    ;;
esac

echo "try it:  $CMD_NAME"
