#!/usr/bin/env bash
# mars — developer install (install-dev.sh)
#
# This is the CONTRIBUTOR install path, not the end-user install. It wires
# the `mars` command up to run TypeScript directly from this checkout via
# `tsx`, so edits to orchestrator/src/** go live immediately with no rebuild.
#
# Requires: Bun (or at least Node + npm to install tsx) and a local clone of
# the mars-framework repo. End users should use the prebuilt binary install
# instead — this script intentionally does NOT download a release.

set -euo pipefail

echo "mars: developer install (install-dev.sh) — edits to orchestrator/src/** go live; requires Bun." >&2

CMD_NAME="${ORCHESTRATOR_CMD:-mars}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORCH_DIR="$REPO_ROOT/orchestrator"
ENTRY="$ORCH_DIR/src/cli.ts"
TSX_BIN="$ORCH_DIR/node_modules/.bin/tsx"

if [[ ! -f "$ENTRY" ]]; then
  echo "error: cli entry not found at $ENTRY" >&2
  exit 1
fi

if [[ ! -x "$TSX_BIN" ]]; then
  echo "tsx not found at $TSX_BIN — running 'npm install' in $ORCH_DIR" >&2
  (cd "$ORCH_DIR" && npm install)
fi

pick_bin_dir() {
  if [[ -n "${PREFIX:-}" ]]; then
    echo "$PREFIX/bin"
    return
  fi
  for d in "$HOME/.local/bin" "/usr/local/bin" "/opt/homebrew/bin"; do
    if [[ -d "$d" && -w "$d" ]]; then
      echo "$d"
      return
    fi
  done
  mkdir -p "$HOME/.local/bin"
  echo "$HOME/.local/bin"
}

BIN_DIR="$(pick_bin_dir)"
WRAPPER="$BIN_DIR/$CMD_NAME"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by mars-framework/install-dev.sh — do not edit.
# Runs the orchestrator CLI from source via tsx; edits in
# $ORCH_DIR/src are live.
exec "$TSX_BIN" "$ENTRY" "\$@"
EOF
chmod +x "$WRAPPER"

echo "installed: $WRAPPER -> $ENTRY (via $TSX_BIN)"

# Register the framework's .claude/ directory as a Claude Code plugin in
# ~/.claude/settings.json so the mars:* skills become available in Claude Code
# without writing anything into consumer repos.
#
# The plugin root is .claude/ — the directory that contains both
# .claude-plugin/ (plugin.json + marketplace.json manifests) and skills/
# (the actual skill implementations). Claude Code reads plugin.json from
# .claude/.claude-plugin/ to discover the declared skills under .claude/skills/.
#
# NOTE: This is a DEV-WRAPPER convenience step only. For CONSUMER repos the
# plugin activation now happens inside `mars init` — consumers run
# `mars init` in their target repo and get skills + dashboard hint in one
# step. The dev wrapper has no `mars init` step, so it activates here instead.
PLUGIN_DIR="$REPO_ROOT/.claude"
"$TSX_BIN" "$ENTRY" plugin activate "$PLUGIN_DIR"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    echo
    echo "warning: $BIN_DIR is not on your PATH."
    echo "add this to your shell rc:"
    echo "  export PATH=\"$BIN_DIR:\$PATH\""
    ;;
esac

echo "try it:  $CMD_NAME"
