import { readFileSync, readdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Per-stack CLAUDE.md catalogue.
 *
 * A deterministic, offline-readable artifact keyed by the same supervisor
 * names that `detect-stack` emits. The catalogue is committed under
 * `src/init/templates/per-stack/` and is regenerated by the maintainer-only
 * script `scripts/regen-per-stack-catalogue.mjs`. `mars init` reads from
 * this catalogue and never triggers any network fetch.
 *
 * The `generic` entry is the baseline returned for unknown supervisor keys.
 */

const moduleDir = (): string => dirname(fileURLToPath(import.meta.url))

const catalogueDir = (): string =>
  resolve(moduleDir(), 'templates', 'per-stack')

/**
 * Frozen list of every supervisor name `detect-stack.ts` can emit, plus the
 * baseline `generic` entry used as the fallback for unknown keys. The regen
 * script writes one `<name>.md` file per entry; the order is fixed so the
 * regenerated tree is byte-identical across runs.
 */
export const CATALOGUE_ENTRIES = [
  'generic',
  'baseline-supervisor',
  'react-supervisor',
  'vue-supervisor',
  'svelte-supervisor',
  'angular-supervisor',
  'node-backend-supervisor',
  'python-backend-supervisor',
  'go-supervisor',
  'rust-supervisor',
  'infra-supervisor',
  'flutter-supervisor',
  'ios-supervisor',
  'android-supervisor',
  'blockchain-supervisor',
  'ml-supervisor',
] as const

export type CatalogueKey = (typeof CATALOGUE_ENTRIES)[number]

export const GENERIC_BASELINE_KEY: CatalogueKey = 'generic'

/**
 * Deterministic body for one catalogue entry. The body is intentionally
 * minimal in this tracer slice — a follow-up slice will wire the regen
 * script to `fetch-specialist` and richer rendering. The key invariant is
 * that `generateCatalogueEntries()` returns the same Map for the same
 * inputs, byte-for-byte.
 *
 * TODO: replace static bodies with `fetch-specialist`-driven content in a
 * follow-up slice.
 */
const bodyFor = (name: string): string => {
  if (name === 'generic') {
    return [
      '# Generic Supervisor (baseline)',
      '',
      'This is the baseline CLAUDE.md catalogue entry. It is used when no',
      'stack-specific entry matches the supervisor for a given folder.',
      '',
      '- Implement only what the task prompt asks for.',
      '- Follow the project\'s existing conventions and test style.',
      '- Escalate cross-domain or architectural changes to the orchestrator.',
      '',
    ].join('\n')
  }
  const title = name
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
  return [
    `# ${title}`,
    '',
    `Stack-specific CLAUDE.md catalogue entry for \`${name}\`.`,
    '',
    '- Implement only what the task prompt asks for.',
    '- Follow the conventions native to this stack.',
    '- Escalate cross-domain or architectural changes to the orchestrator.',
    '',
  ].join('\n')
}

/**
 * Generate the in-memory catalogue. Pure and deterministic: calling this
 * twice with no arguments must return Maps whose entries are equal in key
 * order and byte-equal in values. The maintainer regen script consumes
 * this and writes one file per entry.
 */
export const generateCatalogueEntries = (): Map<string, string> => {
  const out = new Map<string, string>()
  for (const name of CATALOGUE_ENTRIES) {
    out.set(name, bodyFor(name))
  }
  return out
}

const isMdFile = (filename: string): filename is `${string}.md` =>
  filename.endsWith('.md')

/**
 * Load the committed catalogue from disk. Returns a Map keyed by supervisor
 * name (file basename without `.md`). Throws if the catalogue directory is
 * missing or empty — that signals the regen script has never been run.
 */
export const loadCatalogue = (): Map<string, string> => {
  const dir = catalogueDir()
  const entries = readdirSync(dir).filter(isMdFile).sort()
  if (entries.length === 0) {
    throw new Error(
      `per-stack catalogue is empty at ${dir}; run scripts/regen-per-stack-catalogue.mjs`,
    )
  }
  const out = new Map<string, string>()
  for (const file of entries) {
    const key = file.slice(0, -'.md'.length)
    out.set(key, readFileSync(resolve(dir, file), 'utf8'))
  }
  if (!out.has(GENERIC_BASELINE_KEY)) {
    throw new Error(
      `per-stack catalogue is missing the '${GENERIC_BASELINE_KEY}' baseline entry`,
    )
  }
  return out
}

/**
 * Look up a catalogue entry by supervisor name. Returns the generic
 * baseline body for unknown keys so callers never have to handle `null`.
 */
export const lookupCatalogue = (
  catalogue: ReadonlyMap<string, string>,
  supervisorName: string,
): string => {
  const hit = catalogue.get(supervisorName)
  if (hit !== undefined) return hit
  const baseline = catalogue.get(GENERIC_BASELINE_KEY)
  if (baseline === undefined) {
    throw new Error(
      `per-stack catalogue is missing the '${GENERIC_BASELINE_KEY}' baseline entry`,
    )
  }
  return baseline
}

export const catalogueDirectory = catalogueDir
