import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { relative, resolve } from 'node:path'
import {
  agentsMdPathForScope,
  removeAgentsBlock,
  upsertAgentsBlock,
} from './agents-md'
import type { SupervisorSpec } from './detect-stack'

export type SupervisorOutcomeKind = 'hit' | 'miss' | 'error'

export interface VerifyStepEntry {
  name: string
  cmd: string
  args: string[]
  required: boolean
}

export interface RenderedSupervisor {
  spec: SupervisorSpec
  content: string
  outcome: SupervisorOutcomeKind
  triedSlugs: string[]
  externalSource: { slug: string; path: string } | null
  verify?: VerifyStepEntry[]
}

export interface WriteContext {
  repoRoot: string
  supervisorsDir: string
  supervisorsManifest: string
}

export interface StackSummary {
  languages: string[]
  frameworks: string[]
  infra: string[]
  mobile: string[]
  specialized: string[]
}

export interface WriteResult {
  supervisorsDir: string
  written: string[]
  removed: string[]
  outcomes: Array<{
    name: string
    outcome: SupervisorOutcomeKind
    triedSlugs: string[]
    externalSource: { slug: string; path: string } | null
  }>
}

interface PreviousManifestEntry {
  name: string
  scope: string
}

const readPreviousManifest = (manifestPath: string): PreviousManifestEntry[] => {
  if (!existsSync(manifestPath)) return []
  try {
    const raw = readFileSync(manifestPath, 'utf8')
    const parsed = JSON.parse(raw) as {
      supervisors?: Array<{ name?: string; scope?: string }>
    }
    if (!parsed.supervisors) return []
    return parsed.supervisors
      .filter((s): s is { name: string; scope?: string } => typeof s?.name === 'string')
      .map((s) => ({ name: s.name, scope: s.scope ?? '.' }))
  } catch {
    return []
  }
}

export const writeSupervisors = (
  ctx: WriteContext,
  stack: StackSummary,
  rendered: RenderedSupervisor[],
  now: () => string = () => new Date().toISOString(),
): WriteResult => {
  mkdirSync(ctx.supervisorsDir, { recursive: true })

  const previous = readPreviousManifest(ctx.supervisorsManifest)
  const currentKeys = new Set(
    rendered.map((r) => `${r.spec.name}::${r.spec.scope}`),
  )

  const written: string[] = []
  const removed: string[] = []

  for (const prev of previous) {
    const key = `${prev.name}::${prev.scope}`
    if (currentKeys.has(key)) continue
    const filePath = agentsMdPathForScope(ctx.repoRoot, prev.scope)
    const result = removeAgentsBlock(filePath, prev.name, prev.scope)
    if (result.removed) removed.push(relative(ctx.repoRoot, filePath))
  }

  const entries = rendered.map((r) => {
    const scope = r.spec.scope
    const filePath = agentsMdPathForScope(ctx.repoRoot, scope)
    upsertAgentsBlock({
      filePath,
      supervisorName: r.spec.name,
      scope,
      body: r.content,
    })
    const relPath = relative(ctx.repoRoot, filePath)
    if (!written.includes(relPath)) written.push(relPath)
    return {
      name: r.spec.name,
      persona: r.spec.persona,
      kind: r.spec.kind,
      scope,
      path: relPath,
      outcome: r.outcome,
      triedSlugs: r.triedSlugs,
      externalSource: r.externalSource,
      lines: r.content.split('\n').length,
      ...(r.verify ? { verify: r.verify } : {}),
    }
  })

  const manifest = {
    version: 1 as const,
    generatedAt: now(),
    stack,
    supervisors: entries,
    removed,
  }
  writeFileSync(
    ctx.supervisorsManifest,
    JSON.stringify(manifest, null, 2) + '\n',
    'utf8',
  )
  written.push(relative(ctx.repoRoot, ctx.supervisorsManifest))

  const indexMd = `# Mars Supervisors

This directory tracks specialized supervisor metadata generated by \`mars init\`.
The supervisor prose lives in per-scope \`AGENTS.md\` files (loaded by Claude Code's
hierarchical agent guidance) — this directory only stores the \`manifest.json\` index.

Re-run \`mars init --force\` to regenerate.

Generated: ${manifest.generatedAt}

## Detected stack

- Languages: ${stack.languages.join(', ') || '—'}
- Frameworks: ${stack.frameworks.join(', ') || '—'}
- Infra: ${stack.infra.join(', ') || '—'}
- Mobile: ${stack.mobile.join(', ') || '—'}
- Specialized: ${stack.specialized.join(', ') || '—'}

## Supervisors

${entries.map((e) => `- **${e.name}** (${e.persona}) — ${e.kind} — scope: ${e.scope} — ${e.lines} lines — ${e.outcome}${e.externalSource ? ` (${e.externalSource.slug})` : ''}`).join('\n') || '_(none)_'}
`
  const indexPath = resolve(ctx.supervisorsDir, 'README.md')
  writeFileSync(indexPath, indexMd, 'utf8')
  written.push(relative(ctx.repoRoot, indexPath))

  return {
    supervisorsDir: ctx.supervisorsDir,
    written,
    removed,
    outcomes: entries.map((e) => ({
      name: e.name,
      outcome: e.outcome,
      triedSlugs: e.triedSlugs,
      externalSource: e.externalSource,
    })),
  }
}
