import { raiseInboxItem } from '../src/mastra/lib/inbox'

const main = async () => {
  const now = new Date().toISOString()
  const id = await raiseInboxItem({
    kind: 'desync.task-row-missing',
    category: 'daemon',
    priority: 'high',
    title: 'desync 2af0f3a4: branch landed, task row purged — no remediation column to write',
    body: [
      'Task 2af0f3a4 reached an unrecoverable desync state that neither',
      'remediation path (a) land branch into main, nor (b) flip the task row',
      'to failed-with-error, can address as written.',
      '',
      'Investigation:',
      '- git: branch task/2af0f3a4 tip is d3322b550388da6b7cd8e30959960c27262136d4',
      '  ("feat(orchestrator): write per-scope AGENTS.md from mars init"). It IS',
      '  an ancestor of main (`git merge-base --is-ancestor task/2af0f3a4 main`',
      '  succeeds). main is ~20 commits ahead of the branch tip.',
      '- queue.db: NO row for id 2af0f3a4 in the current tasks table. The row',
      '  was already purged. The most recent backup',
      '  (.mars/queue.db.bak.selfheal-purge) still has it:',
      '    id=2af0f3a4 status=failed branch=(empty) error="daemon restart while task was running"',
      '- watch.log: 2026-05-09T07:30:38 [implement] 2af0f3a4 dispatching;',
      '             2026-05-09T08:25:23 [reconcile] task 2af0f3a4 was running on prior daemon; marking failed',
      '- sweeper.log: between 2026-05-09T12:47:39 and 2026-05-09T15:28:21 the',
      '  sweeper logged ~16 self-heal enqueues for the same desync, spawning',
      '  cascading self-heal tasks (mars-645d2338 — the current self-heal — is',
      '  one of them). The recursion implies the originating row was fine, but',
      '  the desync detector kept matching the orphan branch ref because the',
      '  task ID prefix still resolves to a row that the sweeper considered',
      '  failed-yet-merged.',
      '',
      'Why neither remediation applies:',
      '(a) Land task/2af0f3a4 into main — already done. Branch tip is an ancestor',
      '    of main; main is strictly ahead. There is nothing to fast-forward.',
      '(b) Update the task row with an explanatory error — there is no row to',
      '    update. queue.db has zero matches for id=2af0f3a4. Re-creating a row',
      '    just to write into its `error` column would silently fabricate state',
      '    the orchestrator never produced.',
      '',
      'What blocks autonomous resolution:',
      '- The sweeper detector still considers task/2af0f3a4 a desync even though',
      '  the row is gone. Either the detector should skip branches whose task',
      '  row no longer exists, or the orphan branch ref task/2af0f3a4 should be',
      '  pruned now that it has been merged. Both decisions affect future',
      '  desync handling and should not be made silently inside a self-heal',
      '  worker.',
      '- The cascading recursion (16+ self-heal tasks for one ghost branch) is',
      '  itself a separate concern — even if this incident is closed, the',
      '  recursion guard for desync self-heal needs review.',
      '',
      'Suggested follow-ups (not executed by this self-heal):',
      '1. Prune branch ref task/2af0f3a4 (it is fully merged into main).',
      '2. Teach the desync sweeper to no-op when no tasks row exists for the',
      '   branch (or alternatively, when branch tip is already an ancestor of',
      '   main AND no row exists, treat as already-resolved and stop enqueuing',
      '   self-heal tasks).',
      '3. Review the orphan worktree directory .mars/worktrees/2af0f3a4/ — its',
      '   .git pointer references .git/worktrees/2af0f3a4 which no longer',
      '   exists; `git worktree list` shows it as detached HEAD 0000000.',
      '   Per task instructions the worktree was not removed.',
    ].join('\n'),
    payload: {
      taskId: '2af0f3a4',
      branch: 'task/2af0f3a4',
      branchTip: 'd3322b550388da6b7cd8e30959960c27262136d4',
      branchIsAncestorOfMain: true,
      taskRowPresent: false,
      lastKnownStatus: 'failed',
      lastKnownError: 'daemon restart while task was running',
      worktreePath: '.mars/worktrees/2af0f3a4',
      observedSelfHealCascade: 16,
      currentSelfHealTaskId: 'mars-645d2338',
    },
    context: {
      repoRoot: process.env.MARS_REPO ?? null,
      raisedAt: now,
    },
    raisedBy: 'agent:self-heal-desync',
    signature: 'desync:2af0f3a4:task-row-missing',
    occurrence: {
      at: now,
      selfHealTaskId: 'mars-645d2338',
    },
  })
  console.log(`raised inbox item ${id}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
