#!/usr/bin/env node
// Regenerate src/version.ts from package.json so the version is inlined
// at the source level. Runs as a prebuild/pretest hook; safe to invoke
// directly with `node scripts/sync-version.mjs`.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(here, '..')
const pkgPath = resolve(projectRoot, 'package.json')
const outPath = resolve(projectRoot, 'src', 'version.ts')

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
const version = pkg.version
if (typeof version !== 'string' || version.length === 0) {
  throw new Error(`package.json missing a "version" string at ${pkgPath}`)
}

const content = `// AUTOGENERATED by scripts/sync-version.mjs from package.json.
// Do not edit by hand — run \`node scripts/sync-version.mjs\` (or any
// npm script with the wired prebuild/pretest hook) to regenerate.
//
// The constant is inlined at the source level so a compiled binary
// does not need package.json alongside it at runtime.
export const MARS_VERSION = ${JSON.stringify(version)}
`

writeFileSync(outPath, content)
process.stdout.write(`synced MARS_VERSION = ${version}\n`)
