// AUTOGENERATED by scripts/sync-version.mjs from an explicit argument or package.json.
// Do not edit by hand — run `node scripts/sync-version.mjs [version]` (or
// any npm script with the wired prebuild/pretest hook) to regenerate.
//
// The constant is inlined at the source level so a compiled binary
// does not need package.json alongside it at runtime.
export const MARS_VERSION = "0.0.0-dev"
