// AUTOGENERATED by scripts/sync-version.mjs from package.json.
// Do not edit by hand — run `node scripts/sync-version.mjs` (or any
// npm script with the wired prebuild/pretest hook) to regenerate.
//
// The constant is inlined at the source level so a compiled binary
// does not need package.json alongside it at runtime.
export const MARS_VERSION = "0.1.1"
